"""add auth fields to users, saved_addresses, saved_cars

Revision ID: 30c7af88035b
Revises: e4f3ff1e8ed6
Create Date: 2026-04-06 22:24:34.551624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c7af88035b'
down_revision = 'e4f3ff1e8ed6'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'saved_addresses',
        sa.Column('id',         sa.Integer(),      nullable=False),
        sa.Column('user_id',    sa.Integer(),      nullable=False),
        sa.Column('label',      sa.String(80),     nullable=False),
        sa.Column('address',    sa.String(512),    nullable=False),
        sa.Column('sort_order', sa.Integer(),      nullable=False, server_default='0'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                name=op.f('fk_saved_addresses_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_addresses')),
        sa.UniqueConstraint('user_id', 'label', name='uq_saved_addresses_user_id_label'),
    )
    op.create_index(op.f('ix_saved_addresses_user_id'), 'saved_addresses', ['user_id'])

    op.create_table(
        'saved_cars',
        sa.Column('id',         sa.Integer(),      nullable=False),
        sa.Column('user_id',    sa.Integer(),      nullable=False),
        sa.Column('name',       sa.String(80),     nullable=False),
        sa.Column('mpg',        sa.Float(),        nullable=False),
        sa.Column('fuel_type',  sa.String(20),     nullable=False, server_default='gasoline'),
        sa.Column('is_default', sa.Boolean(),      nullable=False, server_default='0'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                name=op.f('fk_saved_cars_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_cars')),
        sa.UniqueConstraint('user_id', 'name', name='uq_saved_cars_user_id_name'),
    )
    op.create_index(op.f('ix_saved_cars_user_id'), 'saved_cars', ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username',      sa.String(length=64),  nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    op.create_table('_alembic_tmp_trips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('start_loc', sa.VARCHAR(), nullable=False),
    sa.Column('end_loc', sa.VARCHAR(), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=20), nullable=False),
    sa.Column('car_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('miles', sa.FLOAT(), nullable=False),
    sa.Column('co2_kg', sa.FLOAT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trips_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    # ### end Alembic commands ###
